import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import SessionWrapper from "@/app/components/SessionWrapper";
// import { Dashboard } from "./components/menu-editor";
import React from "react"; // Add this import
import { DashboardLayout } from "./components/dashboard-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <DashboardLayout>
        <React.Fragment>
          {" "}
          {/* Replace <div> with <React.Fragment> */}
          <div className={inter.className}>{children}</div>
        </React.Fragment>
      </DashboardLayout>
    </SessionWrapper>
  );
}
